server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: campaign-api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: campaign-analytics
          uri: lb://campaign-analytics
          predicates:
            - Path=/api/analytics/**
        - id: campaign-integration
          uri: lb://campaign-integration
          predicates:
            - Path=/api/integrate/**
        - id: campaign-payment
          uri: lb://campaign-payment
          predicates:
            - Path=/api/payments/**
  main:
    web-application-type: reactive
  datasource:
    url: jdbc:postgresql://localhost:5432/campaign_db?currentSchema=api_gateway
    username: 'postgres'
    password: 'R@h!l@410'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
